services:
  ac-database:
    environment:
      TZ: ${TZ}

  ac-worldserver:
    environment:
      TZ: ${TZ}
    volumes:
      - ./modules:/azerothcore/modules:rw
  ac-authserver:
    environment:
      TZ: ${TZ}
  ac-client-data-init:
    networks:
      - ac-network
      