services:
  ac-database:
    environment:
      TZ: ${TZ}
    volumes:
      - ${DOCKER_VOL_DB_CNF}:/etc/mysql/conf.d
  ac-db-import:
    environment:
      TZ: ${TZ}
  ac-worldserver:
    environment:
      TZ: ${TZ}
    volumes:
      - ./modules:/azerothcore/modules:rw
      - ${WOTLK_LUA_SCRIPT_DIR}:/azerothcore/lua_scripts:rw
  ac-authserver:
    environment:
      TZ: ${TZ}
  ac-client-data-init:
    networks:
      - ac-network